### ISSUE TITLE
forcing utf-8 read and write will break building the auctex package

### ISSUE THREAD

**Issue by bluewww** [sam217pa/emacs-config#1]
Don't
```
(setq 
coding-system-for-read 'utf-8
coding-system-for-write 'utf-8)
 ```

because it will break building some packages because they use sometimes different encodings than utf-8. If you forcefully parse those as utf-8 things might break. For me the auctex package broke this way.

`(prefer-coding-system 'utf-8) `
is enough since it ensures that any future file is going to be utf-8.

**Comment by sam217pa** [comment]
Well thanks for your advice,
my bad for not replying to you ! 
Should be fixed by now.

Thank you again !
